<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Grd_analysis_report extends MY_controller{
	
	public function __construct(){
		parent:: __construct();
		$this->loggedOut();
		$this->load->model('Alam','alam');
	}
	
	public function index(){
		$data['school_photo'] = $this->alam->selectA('school_photo','*');
		$data['school_setting'] = $this->alam->selectA('school_setting','*');
		$data['topper_list'] = $this->alam->topper_list();
		$data['subj_head'] = $this->alam->selectA('temp_report_card','distinct (subj1_nm),subj2_nm,subj3_nm,subj4_nm,subj5_nm,subj6_nm,subj1_nm,subj7_nm,subj8_nm,subj9_nm,subj10_nm,subj11_nm,subj12_nm,subj13_nm,subj14_nm,subj15_nm');
		$data['a1'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'A1')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'A1')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'A1')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'A1')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'A1')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'A1')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'A1')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'A1')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'A1')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'A1')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'A1')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'A1')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'A1')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'A1')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'A1')subj15_gr","subj1_grd = 'A1'");
		
		$data['a2'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'A2')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'A2')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'A2')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'A2')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'A2')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'A2')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'A2')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'A2')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'A2')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'A2')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'A2')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'A2')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'A2')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'A2')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'A2')subj15_gr","subj1_grd = 'A2'");
		
		
		$data['b1'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'B1')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'B1')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'B1')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'B1')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'B1')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'B1')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'B1')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'B1')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'B1')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'B1')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'B1')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'B1')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'B1')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'B1')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'B1')subj15_gr","subj1_grd = 'B1'");
		
		
		$data['b2'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'B2')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'B2')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'B2')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'B2')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'B2')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'B2')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'B2')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'B2')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'B2')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'B2')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'B2')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'B2')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'B2')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'B2')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'B2')subj15_gr","subj1_grd = 'B2'");
		
		$data['c1'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'C1')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'C1')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'C1')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'C1')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'C1')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'C1')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'C1')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'C1')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'C1')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'C1')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'C1')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'C1')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'C1')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'C1')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'C1')subj15_gr","subj1_grd = 'C1'");
		
		
		$data['c2'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'C2')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'C2')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'C2')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'C2')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'C2')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'C2')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'C2')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'C2')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'C2')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'C2')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'C2')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'C2')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'C2')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'C2')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'C2')subj15_gr","subj1_grd = 'C2'");
		
		$data['d'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'D')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'D')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'D')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'D')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'D')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'D')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'D')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'D')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'D')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'D')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'D')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'D')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'D')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'D')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'D')subj15_gr","subj1_grd = 'D'");
		
		$data['e'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'E')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'E')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'E')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'E')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'E')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'E')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'E')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'E')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'E')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'E')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'E')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'E')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'E')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'E')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'E')subj15_gr","subj1_grd = 'E'");
		
		$data['ab'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = 'AB')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = 'AB')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = 'AB')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = 'AB')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = 'AB')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = 'AB')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = 'AB')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = 'AB')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = 'AB')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = 'AB')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = 'AB')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = 'AB')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = 'AB')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = 'AB')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = 'AB')subj15_gr","subj1_grd = 'AB'");
		
		$data['dash'] = $this->alam->selectA('temp_report_card',"count(*),(SELECT count(*) FROM `temp_report_card` WHERE subj1_grd = '-')subj1_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj2_grd = '-')subj2_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj3_grd = '-')subj3_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj4_grd = '-')subj4_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj5_grd = '-')subj5_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj6_grd = '-')subj6_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj7_grd = '-')subj7_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj8_grd = '-')subj8_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj9_grd = '-')subj9_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj10_grd = '-')subj10_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj11_grd = '-')subj11_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj12_grd = '-')subj12_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj13_grd = '-')subj13_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj14_grd = '-')subj14_gr,(SELECT count(*) FROM `temp_report_card` WHERE subj15_grd = '-')subj15_gr","subj1_grd = '-'");
		
		$data['appeared'] = $this->alam->selectA('temp_report_card',"count(subj1_grd),(SELECT count(subj1_grd) FROM `temp_report_card`)subj1_p,(SELECT count(subj2_grd) FROM `temp_report_card`)subj2_p,(SELECT count(subj3_grd) FROM `temp_report_card`)subj3_p,(SELECT count(subj4_grd) FROM `temp_report_card`)subj4_p,(SELECT count(subj5_grd) FROM `temp_report_card`)subj5_p,(SELECT count(subj6_grd) FROM `temp_report_card`)subj6_p,(SELECT count(subj7_grd) FROM `temp_report_card`)subj7_p,(SELECT count(subj8_grd) FROM `temp_report_card`)subj8_p,(SELECT count(subj9_grd) FROM `temp_report_card`)subj9_p,(SELECT count(subj10_grd) FROM `temp_report_card`)subj10_p,(SELECT count(subj11_grd) FROM `temp_report_card`)subj11_p,(SELECT count(subj12_grd) FROM `temp_report_card`)subj12_p,(SELECT count(subj13_grd) FROM `temp_report_card`)subj13_p,(SELECT count(subj14_grd) FROM `temp_report_card`)subj14_p,(SELECT count(subj15_grd) FROM `temp_report_card`)subj15_p");
		
		$this->load->view('report_card/grd_analysis_pdf',$data);
		
		$html = $this->output->get_output();
		$this->load->library('pdf');
		$this->dompdf->loadHtml($html);
		$this->dompdf->setPaper('A4', 'landscape');
		$this->dompdf->render();
		$this->dompdf->stream("Grade_analysis.pdf", array("Attachment"=>0));
	}
}